apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod2
spec:
  containers:
  - image: nginx
    name: task-pv-container2
    ports:
    - containerPort: 80
      name: http-server2
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-pv-storage2
  volumes:
  - persistentVolumeClaim:
      claimName: my-pv-claim2
    name: my-pv-storage2

