apiVersion: batch/v1
kind: Job
metadata:
  name: counter
spec:
  completions: 2
  completionMode: Indexed
  template:
    metadata:
      name: counter
    spec:
      containers:
      - name: counter
        image: busybox:1.36
        command:
        - "sh"
        - "-c"
        - "for i in 1234 ; do echo $i ; done"
      restartPolicy: Never
